### ISSUE TITLE
error font

### ISSUE THREAD

**Issue by ghost** [Firewolf05/dotfiles#2]
Your font use please

**Comment by GeorgeBnrs** [comment]
font for what? all the fonts that are used in polybar are mentioned in its config

**Comment by ghost** [comment]
> font for what? all the fonts that are used in polybar are mentioned in its config

neofetch please, i using cinnamon but i want use this neofetch

**Comment by GeorgeBnrs** [comment]
> > font for what? all the fonts that are used in polybar are mentioned in its config
> 
> neofetch please, i using cinnamon but i want use this neofetch 

FantasqueSansMono Nerd Font

**Comment by ghost** [comment]
> FantasqueSansMono Nerd Font
is this support icon in neofetch?

**Comment by GeorgeBnrs** [comment]
> > FantasqueSansMono Nerd Font
> is this support icon in neofetch?

yeah, all nerd fonts have icons, that's their point

**Comment by lebakhai13** [comment]
> 

thanks

**Comment by ghost** [comment]
> > > FantasqueSansMono Nerd Font
> > > is this support icon in neofetch?
> 
> yeah, all nerd fonts have icons, that's their point

thanks
